---
output_dir: "."
title: "My first notebook"
author: "Arnaldo Silva"
date: "11 December 2020"
output:
  html_document:
    toc: true 
    toc_depth: 4
    toc_float: true
---

# This is not a comment in R Markdown 
\

<!-- This is a comment -->

<!-- Headings -->

# Heading 1

## Heading 2

### Heading 3

#### Heading 4
\

# Inline text formatting 
\
to make text bold use **double asteriks** or __double underscore__

To make make text italic use *asteriks* or _underscore_

To make text superscript use ^caret^

To make subscripte use ~tilde~

To mare text as inline code use 'backticks'

To make text strikethrough use ~~tilde~~

\

# Links

Link to webpage [Link to share document] (https://docs.google.com/document/d/1N8gPLlwWvviLO4S4v5DgsZrafEeV2r4IeHu3KHDrWNc/edit#) 



\

# Line Breaks
\
Text here

# Footnotes

To indicate a footnoye use [^1] and a second footnote [^2]

[^1]: this is the first footnote 
[^2]: this is the second foot note 


# Lists

Ordered List (for sublist use 4 spaces, to indent item )

1. Item 1
2. Item 2 
3. Item 3
    a.Item 3a
        i. Item 3ai
    b. Item 3b
4. Item 4

\

Unordered List (*, +, -)

+ Item 1 
+ Item 2 
    + Item 2.1 
+ Item 3 

\

Task List:
- [] an unchecked Item
- [x] checked item 

\

# Inserting Figures

\

# Tables

| column 1 | Column 2|
|----------|---------|
|item 1,1  |item 1, 2|
|item 2.1  |item 2, 2|


| Left alighn  | Centre align| Right Align    |
|:----------   |:---------:    | --------:    |
|item 1,1      |item 1, 2      | item 1.3     |
|item 2.1      |item 2, 2      | item 2.3     |



\

# Blocks

>Example of block
>
> Some text

```
print ("Hello world")
x<-2+3
print (X)
```

# Table of Contents 


# References example 






